##OS: MacOS-latest
##Toolchain: llvm(clang/clang++)
##BuildTool: cmake
    ##WithCfgType: RelWithDebInfo, DiagASAN, DiagTSAN
##TestTool: ctest
##DepLibs: gtest

name: MacOS-CMake-GTest

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: |
        brew install cmake

    - name: Install GTest
      run: |
        brew install googletest

    - name: Build&Test RelWithDebInfo
      run: |
        mkdir Dir4RelWithDebInfo
        cd Dir4RelWithDebInfo
        cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo ..
        cmake --build . 
        ctest

    - name: Build&Test DiagASAN
      run: |
        mkdir Dir4DiagASAN
        cd Dir4DiagASAN
        cmake -DCMAKE_BUILD_TYPE:STRING=DiagASAN ..
        cmake --build . 
        ctest

    - name: Build&Test DiagTSAN
      run: |
        mkdir Dir4DiagTSAN
        cd Dir4DiagTSAN
        cmake -DCMAKE_BUILD_TYPE:STRING=DiagTSAN ..
        cmake --build .
        ctest
