# OS: MacOS-latest
# Toolchain: llvm(clang/clang++)
# BuildTool: cmake
#   WithCfgType: RelWithDebInfo, DiagASAN, DiagTSAN
# TestTool: ctest
# DepLibs: gtest

name: MacOS-CMake-GTest

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake googletest llvm

    - name: Setup environment
      run: |
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV

    - name: Build&Test RelWithDebInfo
      run: |
        mkdir -p Dir4RelWithDebInfo
        cd Dir4RelWithDebInfo
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
              -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
              ..
        cmake --build . --parallel
        ctest --output-on-failure

    - name: Build&Test DiagASAN
      run: |
        mkdir -p Dir4DiagASAN
        cd Dir4DiagASAN
        cmake -DCMAKE_BUILD_TYPE=DiagASAN \
              -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
              -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
              ..
        cmake --build . --parallel
        ctest --output-on-failure

    - name: Build&Test DiagTSAN
      run: |
        mkdir -p Dir4DiagTSAN
        cd Dir4DiagTSAN
        cmake -DCMAKE_BUILD_TYPE=DiagTSAN \
              -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
              -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
              ..
        cmake --build . --parallel
        ctest --output-on-failure

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-macos
        path: |
          Dir4*/Testing/
          Dir4*/Test/
